#pragma once

#include "ctre/phoenix6/SignalLogger.hpp"

#include "wpi/commands2/CommandPtr.hpp"
#include "wpi/commands2/SubsystemBase.hpp"
#include "wpi/commands2/sysid/SysIdRoutine.hpp"
#include "wpi/system/Notifier.hpp"

#include "generated/TunerConstants.hpp"

using namespace ctre::phoenix6;

namespace subsystems {

/**
 * \brief Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
class CommandSwerveDrivetrain : public wpi::cmd::SubsystemBase, public TunerSwerveDrivetrain {
    static constexpr wpi::units::second_t SIM_LOOP_PERIOD = 4_ms;
    std::unique_ptr<wpi::Notifier> simNotifier;
    wpi::units::second_t lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    static constexpr wpi::math::Rotation2d kBlueAlliancePerspectiveRotation{0_deg};
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    static constexpr wpi::math::Rotation2d kRedAlliancePerspectiveRotation{180_deg};
    /* Keep track if we've ever applied the operator perspective before or not */
    bool hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    swerve::requests::ApplyRobotVelocity pathApplyRobotVelocity;

    /* Swerve requests to apply during SysId characterization */
    swerve::requests::SysIdSwerveTranslation translationCharacterization;
    swerve::requests::SysIdSwerveSteerGains steerCharacterization;
    swerve::requests::SysIdSwerveRotation rotationCharacterization;

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    wpi::cmd::sysid::SysIdRoutine sysIdRoutineTranslation{
        wpi::cmd::sysid::Config{
            std::nullopt, // Use default ramp rate (1 V/s)
            4_V,          // Reduce dynamic step voltage to 4 V to prevent brownout
            std::nullopt, // Use default timeout (10 s)
            // Log state with SignalLogger class
            [](wpi::sysid::State state)
            {
                SignalLogger::WriteString("SysIdTranslation_State", wpi::sysid::SysIdRoutineLog::StateEnumToString(state));
            }
        },
        wpi::cmd::sysid::Mechanism{
            [this](wpi::units::volt_t output) { SetControl(translationCharacterization.WithVolts(output)); },
            {},
            this
        }
    };

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    wpi::cmd::sysid::SysIdRoutine sysIdRoutineSteer{
        wpi::cmd::sysid::Config{
            std::nullopt, // Use default ramp rate (1 V/s)
            7_V,          // Use dynamic voltage of 7 V
            std::nullopt, // Use default timeout (10 s)
            // Log state with SignalLogger class
            [](wpi::sysid::State state)
            {
                SignalLogger::WriteString("SysIdSteer_State", wpi::sysid::SysIdRoutineLog::StateEnumToString(state));
            }
        },
        wpi::cmd::sysid::Mechanism{
            [this](wpi::units::volt_t output) { SetControl(steerCharacterization.WithVolts(output)); },
            {},
            this
        }
    };

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of swerve::requests::SysIdSwerveRotation for info on importing the log to SysId.
     */
    wpi::cmd::sysid::SysIdRoutine sysIdRoutineRotation{
        wpi::cmd::sysid::Config{
            /* This is in radians per second², but SysId only supports "volts per second" */
            wpi::units::constants::detail::PI_VAL / 6 * (1_V / 1_s),
            /* This is in radians per second, but SysId only supports "volts" */
            wpi::units::constants::detail::PI_VAL * 1_V,
            std::nullopt, // Use default timeout (10 s)
            // Log state with SignalLogger class
            [](wpi::sysid::State state)
            {
                SignalLogger::WriteString("SysIdRotation_State", wpi::sysid::SysIdRoutineLog::StateEnumToString(state));
            }
        },
        wpi::cmd::sysid::Mechanism{
            [this](wpi::units::volt_t output)
            {
                /* output is actually radians per second, but SysId only supports "volts" */
                SetControl(rotationCharacterization.WithRotationalRate(output * (1_rad_per_s / 1_V)));
                /* also log the requested output for SysId */
                SignalLogger::WriteValue("Rotational_Rate", output * (1_rad_per_s / 1_V));
            },
            {},
            this
        }
    };

    /* The SysId routine to test */
    wpi::cmd::sysid::SysIdRoutine *sysIdRoutineToApply = &sysIdRoutineTranslation;

public:
    /**
     * \brief Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them
     * through getters in the classes.
     *
     * \param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * \param modules             Constants for each specific module
     */
    template <std::same_as<SwerveModuleConstants>... ModuleConstants>
    CommandSwerveDrivetrain(swerve::SwerveDrivetrainConstants const &driveTrainConstants, ModuleConstants const &... modules) :
        TunerSwerveDrivetrain{driveTrainConstants, modules...}
    {
        if (utils::IsSimulation()) {
            StartSimThread();
        }
        ConfigureAutoBuilder();
    }

    /**
     * \brief Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them
     * through getters in the classes.
     *
     * \param driveTrainConstants        Drivetrain-wide constants for the swerve drive
     * \param odometryUpdateFrequency    The frequency to run the odometry loop. If
     *                                   unspecified or set to 0 Hz, this is 250 Hz on
     *                                   CAN FD, and 100 Hz on CAN 2.0.
     * \param modules                    Constants for each specific module
     */
    template <std::same_as<SwerveModuleConstants>... ModuleConstants>
    CommandSwerveDrivetrain(
        swerve::SwerveDrivetrainConstants const &driveTrainConstants,
        wpi::units::hertz_t odometryUpdateFrequency,
        ModuleConstants const &... modules
    ) :
        TunerSwerveDrivetrain{driveTrainConstants, odometryUpdateFrequency, modules...}
    {
        if (utils::IsSimulation()) {
            StartSimThread();
        }
        ConfigureAutoBuilder();
    }

    /**
     * \brief Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them
     * through getters in the classes.
     *
     * \param driveTrainConstants        Drivetrain-wide constants for the swerve drive
     * \param odometryUpdateFrequency    The frequency to run the odometry loop. If
     *                                   unspecified or set to 0 Hz, this is 250 Hz on
     *                                   CAN FD, and 100 Hz on CAN 2.0.
     * \param odometryStandardDeviation  The standard deviation for odometry calculation
     * \param visionStandardDeviation    The standard deviation for vision calculation
     * \param modules                    Constants for each specific module
     */
    template <std::same_as<SwerveModuleConstants>... ModuleConstants>
    CommandSwerveDrivetrain(
        swerve::SwerveDrivetrainConstants const &driveTrainConstants,
        wpi::units::hertz_t odometryUpdateFrequency,
        std::array<double, 3> const &odometryStandardDeviation,
        std::array<double, 3> const &visionStandardDeviation,
        ModuleConstants const &... modules
    ) :
        TunerSwerveDrivetrain{
            driveTrainConstants, odometryUpdateFrequency,
            odometryStandardDeviation, visionStandardDeviation, modules...
        }
    {
        if (utils::IsSimulation()) {
            StartSimThread();
        }
        ConfigureAutoBuilder();
    }

    /**
     * \brief Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * This captures the returned swerve request by reference, so it must live
     * for at least as long as the drivetrain. This can be done by storing the
     * request as a member variable of your drivetrain subsystem or robot.
     *
     * \param request Function returning the request to apply
     * \returns Command to run
     */
    template <typename RequestSupplier>
        requires std::is_lvalue_reference_v<std::invoke_result_t<RequestSupplier>> &&
            requires(RequestSupplier req, TunerSwerveDrivetrain &drive) { drive.SetControl(req()); }
    wpi::cmd::CommandPtr ApplyRequest(RequestSupplier request)
    {
        return Run([this, request=std::move(request)] {
            return SetControl(request());
        });
    }

    /**
     * \brief Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * \param request Function returning the request to apply
     * \returns Command to run
     */
    template <typename RequestSupplier>
        requires (!std::is_lvalue_reference_v<std::invoke_result_t<RequestSupplier>>) &&
            requires(RequestSupplier req, TunerSwerveDrivetrain &drive) { drive.SetControl(req()); }
    wpi::cmd::CommandPtr ApplyRequest(RequestSupplier request)
    {
        return Run([this, request=std::move(request)] {
            return SetControl(request());
        });
    }

    void Periodic() override;

    /**
     * \brief Runs the SysId Quasistatic test in the given direction for the routine
     * specified by sysIdRoutineToApply.
     *
     * \param direction Direction of the SysId Quasistatic test
     * \returns Command to run
     */
    wpi::cmd::CommandPtr SysIdQuasistatic(wpi::cmd::sysid::Direction direction)
    {
        return sysIdRoutineToApply->Quasistatic(direction);
    }

    /**
     * \brief Runs the SysId Dynamic test in the given direction for the routine
     * specified by sysIdRoutineToApply.
     *
     * \param direction Direction of the SysId Dynamic test
     * \returns Command to run
     */
    wpi::cmd::CommandPtr SysIdDynamic(wpi::cmd::sysid::Direction direction)
    {
        return sysIdRoutineToApply->Dynamic(direction);
    }

private:
    void ConfigureAutoBuilder();
    void StartSimThread();
};

}
